import type { NextPage } from "next";
import Head from "next/head";
import { ConnectButton, ConnectionStatus } from "../components";
import { Connectors } from "../constants";
import { useConnectionContext } from "../context";

const Home: NextPage = () => {
  const { connect, disconnect } = useConnectionContext();

  return (
    <div>
      <Head>
        <title>Web3 template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex flex-col justify-center h-screen">
          <ConnectionStatus />
          <div className="flex flex-col gap-[44px] my-auto max-w-[367px] mx-auto">
            <ConnectButton
              src="/assets/wcLogo.png"
              label="Wallet Connect"
              connectCallback={() => {
                connect(Connectors.walletConnect);
              }}
            />

            <ConnectButton
              src="/assets/metaMaskLogo.png"
              label="Metamask"
              connectCallback={() => {
                connect(Connectors.metamask);
              }}
            />

            <button
              className="br-[8px] border-2 h-[82px] p-[4px]"
              onClick={() => {
                disconnect();
              }}
            >
              <p>Disconnect</p>
            </button>
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
